---
# export ANSIBLE_STDOUT_CALLBACK=debug
- name: Dump generated ACL for a given OS.
  hosts: localhost
  gather_facts: no
 
  tasks:
  - name: Run this module to generate an ACL
    nleiva.capirca_acl.translate:
      platform: 'ciscoxr'
      def_folder: "sample"
      pol_file: "sample/terms.pol"
    register: testout
  
  - name: Dump the resulting ACL
    debug:
      msg: "{{ testout.message }}"